# Welcome to Jupyter!

In [1]:
# %load Core\ python.py
#!/usr/bin/env python

# # Welcome to Jupyter!

# Core Python

# Variables

# In[3]:


b = 2 # b is integer type
print (b)
b = b*2.0 # Now b is float type
print (b)


# Strings

# In[5]:


string1 = 'Press return to exit'
string2 = 'the program'
print (string1+''+string2) #Strings are concatenated with the plus + operator
print(string1[0:12])


# s = 'Press return to exit'
# s[0] = 'p' # TypeError: 'str' object does not support item assignment

# Tuples

# In[12]:


rec = ('Smith','John',(6,23,68))
lastName,firstName,birthdate = rec
print(firstName)
birthYear = birthdate[2]
print(birthYear)
name = rec[1]+''+rec[0]
print(name)
print(rec[0:2])


# Lists

# In[13]:


a = [1.0,2.0,3.0]
a.append(4.0)
print(a)
a.insert(0,0.0)
print(a)
print(len(a))
a[2:4]=[1.0,1.0] #Modify the selected elements
print(a)


# In[14]:


a = [1.0,2.0,3.0]
b =a #if a is a mutable object, this assignment statement make any chnages to b be reflected in a
b[0] = 5.0
print(a)
c = a[:] # This is an indepent copy of a list a.
c[0] =1.0
print(a)


# In[19]:


a = [[1,2,3],[4,5,6],[7,8,9]] #Matrices can represented as nested lists with each row being an element of the list.
print (a[1])
print (a[1][2])
print (a) # Matrices 

#Arithmetic Operators
# In[22]:


s = 'Hello'
t = 'to you'
a = [1,2,3]
print(3*s)
print(3*a)
print(a+[4,5])
print (s+t)
print (str(3)+s) # 'str' is needed here.Ohterwise,it winds up with unsupported operand types for +: 'int' and 'str'


# In[23]:


import numpy


# In[31]:


import numpy
a = numpy.sinh(3.14159)
b = numpy.cosh(3.14159)
print(a,b)
a +=b
print(a)

a = numpy.sinh(3.14159)
a -=b
print(a)

a = numpy.sinh(3.14159)
a*=b
print(a)

a = numpy.sinh(3.14159)
a/=b
print(a)

a = numpy.sinh(3.14159)
a%=b
print(a)

#Comparison Operators
# In[32]:


a = 2
b = 1.99
c = '2'
print(a>b)
print(a==c)
print(a>b) and not(a!=c)
print(a>b) or (a==b)

#Conditionals
# In[34]:


def sign_of_a(a):
    if a < 0.0:
        sign = 'negative'
    elif a > 0.0:
        sign = 'positive'
    else:
        sign = 'zero'
    return sign
a = numpy.tanh(3.14159)
print(a)
print ('a is ' + sign_of_a(a))

#Loops
# In[36]:


nMax = 5
n = 1
a = [] # Create an empty list
while n < nMax:
    a.append(numpy.sinh(n))
    n = n+1
print(a)


# In[42]:


n =1
a =[]
nMax = 5
for n in range(1,nMax):
    a.append(numpy.sinh(n))
print(a)


# In[50]:


list = ["Jack", "Jill","Tim","Dave"]
name = str(input('Type a name: ')) #Python input prompt
for i in range(len(list)):
    if list[i] == name:
        print(name, 'is number',i+1,'on the list')
        break
else:
    print(name,'is not on the list')


# Type Conversion

# In[59]:


a = 5
b = -3.6
d = '4.0'
print(a+b)
print(int(b))
print(complex(a,b))
print (float(d))
print(eval(d))

#Reading Input
# In[60]:


a = input('Input a: ')
print(a,type(a))
b = eval(a)
print(b,type(b))


#Printing Output

a = 1234.56789
b = [2,4,6,8]




2
4.0
Press return to exitthe program
Press return
John
68
JohnSmith
('Smith', 'John')
[1.0, 2.0, 3.0, 4.0]
[0.0, 1.0, 2.0, 3.0, 4.0]
5
[0.0, 1.0, 1.0, 1.0, 4.0]
[5.0, 2.0, 3.0]
[5.0, 2.0, 3.0]
[4, 5, 6]
6
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
HelloHelloHello
[1, 2, 3, 1, 2, 3, 1, 2, 3]
[1, 2, 3, 4, 5]
Helloto you
3Hello
11.548708597009512 11.591922629945447
23.14063122695496
-0.04321403293593562
133.87173653232009
0.9962720564728149
11.548708597009512
True
False
True
True
0.9962720564728148
a is positive
[1.1752011936438014, 3.626860407847019, 10.017874927409903, 27.28991719712775]
[1.1752011936438014, 3.626860407847019, 10.017874927409903, 27.28991719712775]
Type a name: Dave
Dave is number 4 on the list
1.4
-3
(5-3.6j)
4.0
4.0
Input a: numpy.sinh(-4)
numpy.sinh(-4) <class 'str'>
-27.28991719712775 <class 'numpy.float64'>


In [2]:
# Printing Output
a = 1234.56789
b = [2,4,6,8]
print(a,b)
print('a=',a,'\nb=',b)

1234.56789 [2, 4, 6, 8]
a= 1234.56789 
b= [2, 4, 6, 8]


In [3]:
a = 1234.56789
n = 9876
print('%7.2f'%a)
print('n=%6d'%n) #Pad with 2 spaces
print('n=%06d'%n)#Pad with 2 zeroes
print('%12.4e %6d'%(a,n))

1234.57
n=  9876
n=009876
  1.2346e+03   9876


In [4]:
#Error Control
c = 12.0/0.1

In [5]:
# Functions and Modules
from math import atan
def finite_diff(f,x,h=0.0001):
    df =(f(x+h)-f(x-h))/(2.0*h)
    ddf = (f(x+h)-2.0*f(x)+f(x-h))/h**2
    return df,ddf
x = 0.5
df,ddf = finite_diff(atan,x)
print('First derivative = ',df)
print('Second derivative = ',ddf)

First derivative =  0.7999999995730867
Second derivative =  -0.6399999918915711


In [6]:
def squares(a):
    for i in range(len(a)):
        a[i] = a[i]**2
a = [1,2,3,4]
squares(a)
print(a)

[1, 4, 9, 16]


In [7]:
# Modules
# Mathematics Modules
from math import *
from math import log,sin
print(log(sin(0.5)))

-0.7351666863853142


In [8]:
import math
print(math.log(math.sin(0.5)))

-0.7351666863853142


In [9]:
import math
dir(math)

['__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'acos',
 'acosh',
 'asin',
 'asinh',
 'atan',
 'atan2',
 'atanh',
 'ceil',
 'copysign',
 'cos',
 'cosh',
 'degrees',
 'e',
 'erf',
 'erfc',
 'exp',
 'expm1',
 'fabs',
 'factorial',
 'floor',
 'fmod',
 'frexp',
 'fsum',
 'gamma',
 'gcd',
 'hypot',
 'inf',
 'isclose',
 'isfinite',
 'isinf',
 'isnan',
 'ldexp',
 'lgamma',
 'log',
 'log10',
 'log1p',
 'log2',
 'modf',
 'nan',
 'pi',
 'pow',
 'radians',
 'sin',
 'sinh',
 'sqrt',
 'tan',
 'tanh',
 'tau',
 'trunc']

In [10]:
from cmath import sin
x = 3.0-4.5j
y = 1.2 + 0.8j
z = 0.8
print(x/y)
print(sin(x))
print(sin(z))

(-2.562053133750361e-16-3.75j)
(6.352392998168388+44.55264336489803j)
(0.7173560908995228+0j)


In [11]:
import numpy
dir(numpy)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_arg',
 '_distributor_init',


In [12]:
from numpy import array,float
a = array([[2.0,-1.0],[-1.0,3.0]])
print(a)
b = array([[2,-1],[-1,3]],dtype = float)
print(b)

[[ 2. -1.]
 [-1.  3.]]
[[ 2. -1.]
 [-1.  3.]]


In [13]:
from numpy import arange, zeros, ones, float
a = arange(2,10,2)
print(a)
b = arange(2.0,10.0,2.0)
print(b)
z = zeros((4))
print(z)
y = ones((3,3),dtype = float)
print(y)

[2 4 6 8]
[2. 4. 6. 8.]
[0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [14]:
from numpy import array
a = array([0.0,4.0,9.0,16.0])
print(a/16.0)
print(a-4.0)

[0.     0.25   0.5625 1.    ]
[-4.  0.  5. 12.]


In [16]:
from numpy import array,sqrt,sin
a = array([1.0,4.0,9.0,16.0])
print(sqrt(a))
print(sin(a))
from numpy import array
from math import sqrt
a = array([1.0,4.0,9.0,16.0])
print(sqrt(a[1]))

[1. 2. 3. 4.]
[ 0.84147098 -0.7568025   0.41211849 -0.28790332]
2.0


In [23]:
import numpy
dir(numpy)
?numpy.matrixmultiply
import scipy
dir(scipy)

Object `numpy.matrixmultiply` not found.


['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'LowLevelCallable',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_UFUNC_API',
 '__SCIPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__numpy_version__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_arg',
 '_distributor_init',
 '

In [27]:
from numpy import *
a = array([[4.0,-2.0,1.0],[-2.0,4.0,-2.0],[1.0,-2.0,3.0]])
b = array([1.0,4.0,2.0])
print(dot(b,b))
print(a@b) # Mtrix multiplication
print(diagonal(a))
print(diagonal(a,1))
print(trace(a))
print(argmax(b))
print(identity(3))

21.0
[-2. 10. -1.]
[4. 4. 3.]
[-2. -2.]
11.0
1
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [29]:
c = a
c[0][1] = 2
print(a)

a = array([[4.0,-2.0,1.0],[-2.0,4.0,-2.0],[1.0,-2.0,3.0]])
d =a.copy()
d[0][1] = 2
print(a)

[[ 4.  2.  1.]
 [-2.  4. -2.]
 [ 1. -2.  3.]]
[[ 4. -2.  1.]
 [-2.  4. -2.]
 [ 1. -2.  3.]]
